[package]
name = "rusty-http3"
version = "0.1.0"
authors = ["Pierre-Antoine <pierre-antoine.burdet@hardis.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
